package domain

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

// MediaGenerationTask 媒体生成任务
type MediaGenerationTask struct {
	ID       uuid.UUID `json:"id" db:"id"`
	UserID   uuid.UUID `json:"user_id" db:"user_id"`
	TaskType string    `json:"task_type" db:"task_type"`
	Status   string    `json:"status" db:"status"`

	// 模型和参数
	ModelID     *uuid.UUID      `json:"model_id" db:"model_id"`
	ModelParams json.RawMessage `json:"model_params" db:"model_params"`

	// 输入数据
	TextPrompt        *string `json:"text_prompt" db:"text_prompt"`
	NegativePrompt    *string `json:"negative_prompt" db:"negative_prompt"`
	ReferenceImageURL *string `json:"reference_image_url" db:"reference_image_url"`
	ReferenceVideoURL *string `json:"reference_video_url" db:"reference_video_url"`

	// 输出数据
	ResultURLs     pq.StringArray  `json:"result_urls" db:"result_urls"`
	ResultMetadata json.RawMessage `json:"result_metadata" db:"result_metadata"`

	// 处理信息
	WorkflowID     *string `json:"workflow_id" db:"workflow_id"`
	ExternalTaskID *string `json:"external_task_id" db:"external_task_id"`
	Progress       int     `json:"progress" db:"progress"`
	ErrorMessage   *string `json:"error_message" db:"error_message"`

	// 成本和计费
	EstimatedCost         *float64 `json:"estimated_cost" db:"estimated_cost"`
	ActualCost            *float64 `json:"actual_cost" db:"actual_cost"`
	TokensUsed            *int     `json:"tokens_used" db:"tokens_used"`
	ProcessingTimeSeconds *int     `json:"processing_time_seconds" db:"processing_time_seconds"`

	// 时间戳
	CreatedAt   time.Time  `json:"created_at" db:"created_at"`
	StartedAt   *time.Time `json:"started_at" db:"started_at"`
	CompletedAt *time.Time `json:"completed_at" db:"completed_at"`
	UpdatedAt   time.Time  `json:"updated_at" db:"updated_at"`
}

// MediaTemplate 媒体模板
type MediaTemplate struct {
	ID           uuid.UUID  `json:"id" db:"id"`
	UserID       *uuid.UUID `json:"user_id" db:"user_id"`
	Name         string     `json:"name" db:"name"`
	Description  *string    `json:"description" db:"description"`
	TemplateType string     `json:"template_type" db:"template_type"`

	// 模板配置
	ModelID        *uuid.UUID      `json:"model_id" db:"model_id"`
	DefaultParams  json.RawMessage `json:"default_params" db:"default_params"`
	PromptTemplate *string         `json:"prompt_template" db:"prompt_template"`

	// 可见性和使用
	IsPublic   bool `json:"is_public" db:"is_public"`
	IsFeatured bool `json:"is_featured" db:"is_featured"`
	UsageCount int  `json:"usage_count" db:"usage_count"`

	// 时间戳
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// MediaAsset 媒体资产
type MediaAsset struct {
	ID     uuid.UUID  `json:"id" db:"id"`
	UserID uuid.UUID  `json:"user_id" db:"user_id"`
	TaskID *uuid.UUID `json:"task_id" db:"task_id"`

	// 资产信息
	AssetType    string  `json:"asset_type" db:"asset_type"`
	FileURL      string  `json:"file_url" db:"file_url"`
	ThumbnailURL *string `json:"thumbnail_url" db:"thumbnail_url"`

	// 文件元数据
	FileSize        *int64   `json:"file_size" db:"file_size"`
	Width           *int     `json:"width" db:"width"`
	Height          *int     `json:"height" db:"height"`
	DurationSeconds *float64 `json:"duration_seconds" db:"duration_seconds"`
	Format          *string  `json:"format" db:"format"`

	// 生成元数据
	GenerationParams json.RawMessage `json:"generation_params" db:"generation_params"`
	ModelUsed        *string         `json:"model_used" db:"model_used"`
	PromptUsed       *string         `json:"prompt_used" db:"prompt_used"`

	// 使用和组织
	Title       *string        `json:"title" db:"title"`
	Description *string        `json:"description" db:"description"`
	Tags        pq.StringArray `json:"tags" db:"tags"`
	IsFavorite  bool           `json:"is_favorite" db:"is_favorite"`
	IsPublic    bool           `json:"is_public" db:"is_public"`

	// 使用跟踪
	DownloadCount int `json:"download_count" db:"download_count"`
	ViewCount     int `json:"view_count" db:"view_count"`

	// 时间戳
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// CharacterMedia 角色媒体关联
type CharacterMedia struct {
	ID            uuid.UUID `json:"id" db:"id"`
	CharacterID   uuid.UUID `json:"character_id" db:"character_id"`
	MediaAssetID  uuid.UUID `json:"media_asset_id" db:"media_asset_id"`
	MediaRole     string    `json:"media_role" db:"media_role"`
	IsAutoGenerated bool    `json:"is_auto_generated" db:"is_auto_generated"`
	GenerationPrompt *string `json:"generation_prompt" db:"generation_prompt"`
	CreatedAt     time.Time `json:"created_at" db:"created_at"`
}

// 请求和响应结构

// CreateMediaTaskRequest 创建媒体生成任务请求
type CreateMediaTaskRequest struct {
	TaskType string `json:"task_type" validate:"required,oneof=txt2img img2img img2video txt2video remove_bg animation"`

	// 模型和参数
	ModelID     *uuid.UUID      `json:"model_id,omitempty"`
	ModelParams json.RawMessage `json:"model_params,omitempty"`

	// 输入数据
	TextPrompt        *string `json:"text_prompt,omitempty" validate:"omitempty,max=5000"`
	NegativePrompt    *string `json:"negative_prompt,omitempty" validate:"omitempty,max=2000"`
	ReferenceImageURL *string `json:"reference_image_url,omitempty"`
	ReferenceVideoURL *string `json:"reference_video_url,omitempty"`

	// 角色关联（可选）
	CharacterID *uuid.UUID `json:"character_id,omitempty"`
	MediaRole   *string    `json:"media_role,omitempty" validate:"omitempty,oneof=bg_image cutout_image avatar gallery"`
}

// UpdateMediaTaskRequest 更新媒体生成任务请求
type UpdateMediaTaskRequest struct {
	Status         *string         `json:"status,omitempty" validate:"omitempty,oneof=pending processing completed failed cancelled"`
	Progress       *int            `json:"progress,omitempty" validate:"omitempty,min=0,max=100"`
	ResultURLs     []string        `json:"result_urls,omitempty"`
	ResultMetadata json.RawMessage `json:"result_metadata,omitempty"`
	ErrorMessage   *string         `json:"error_message,omitempty"`
	ActualCost     *float64        `json:"actual_cost,omitempty" validate:"omitempty,min=0"`
	TokensUsed     *int            `json:"tokens_used,omitempty" validate:"omitempty,min=0"`
}

// MediaTaskListRequest 媒体任务列表请求
type MediaTaskListRequest struct {
	UserID     *uuid.UUID `json:"user_id,omitempty"`
	TaskType   *string    `json:"task_type,omitempty"`
	Status     *string    `json:"status,omitempty"`
	DateFrom   *time.Time `json:"date_from,omitempty"`
	DateTo     *time.Time `json:"date_to,omitempty"`
	Page       int        `json:"page" validate:"min=1"`
	Limit      int        `json:"limit" validate:"min=1,max=100"`
}

// MediaTaskResponse 媒体任务响应
type MediaTaskResponse struct {
	*MediaGenerationTask
	ModelName     *string      `json:"model_name,omitempty"`
	GeneratedAssets []MediaAsset `json:"generated_assets,omitempty"`
}

// MediaTaskListResponse 媒体任务列表响应
type MediaTaskListResponse struct {
	Tasks []MediaTaskResponse `json:"tasks"`
	Total int                 `json:"total"`
	Page  int                 `json:"page"`
	Limit int                 `json:"limit"`
}

// CreateMediaTemplateRequest 创建媒体模板请求
type CreateMediaTemplateRequest struct {
	Name         string `json:"name" validate:"required,min=1,max=100"`
	Description  *string `json:"description,omitempty" validate:"omitempty,max=500"`
	TemplateType string `json:"template_type" validate:"required,oneof=txt2img img2img img2video txt2video"`

	ModelID        *uuid.UUID      `json:"model_id,omitempty"`
	DefaultParams  json.RawMessage `json:"default_params,omitempty"`
	PromptTemplate *string         `json:"prompt_template,omitempty" validate:"omitempty,max=2000"`
	IsPublic       bool            `json:"is_public"`
}

// MediaAssetListRequest 媒体资产列表请求
type MediaAssetListRequest struct {
	UserID     *uuid.UUID `json:"user_id,omitempty"`
	AssetType  *string    `json:"asset_type,omitempty" validate:"omitempty,oneof=image video audio"`
	IsPublic   *bool      `json:"is_public,omitempty"`
	IsFavorite *bool      `json:"is_favorite,omitempty"`
	Tag        *string    `json:"tag,omitempty"`
	Search     *string    `json:"search,omitempty"`
	Page       int        `json:"page" validate:"min=1"`
	Limit      int        `json:"limit" validate:"min=1,max=100"`
}

// MediaAssetResponse 媒体资产响应
type MediaAssetResponse struct {
	*MediaAsset
	IsOwner bool `json:"is_owner"`
	CanEdit bool `json:"can_edit"`
}

// MediaAssetListResponse 媒体资产列表响应
type MediaAssetListResponse struct {
	Assets []MediaAssetResponse `json:"assets"`
	Total  int                  `json:"total"`
	Page   int                  `json:"page"`
	Limit  int                  `json:"limit"`
}

// AutoGenerateCharacterImagesRequest 自动生成角色图片请求
type AutoGenerateCharacterImagesRequest struct {
	CharacterID      uuid.UUID `json:"character_id" validate:"required"`
	GenerateBgImage  bool      `json:"generate_bg_image"`
	GenerateCutout   bool      `json:"generate_cutout"`
	CustomPrompt     *string   `json:"custom_prompt,omitempty"`
	UseTemplate      *uuid.UUID `json:"use_template,omitempty"`
}

// AutoGenerateCharacterImagesResponse 自动生成角色图片响应
type AutoGenerateCharacterImagesResponse struct {
	CharacterID   uuid.UUID   `json:"character_id"`
	BgImageTask   *uuid.UUID  `json:"bg_image_task,omitempty"`
	CutoutTask    *uuid.UUID  `json:"cutout_task,omitempty"`
	EstimatedCost float64     `json:"estimated_cost"`
	Tasks         []MediaTaskResponse `json:"tasks"`
}

// 常量定义
const (
	// 任务类型
	TaskTypeTxt2Img   = "txt2img"
	TaskTypeImg2Img   = "img2img"
	TaskTypeImg2Video = "img2video"
	TaskTypeTxt2Video = "txt2video"
	TaskTypeRemoveBG  = "remove_bg"
	TaskTypeAnimation = "animation"

	// 任务状态
	TaskStatusPending    = "pending"
	TaskStatusProcessing = "processing"
	TaskStatusCompleted  = "completed"
	TaskStatusFailed     = "failed"
	TaskStatusCancelled  = "cancelled"

	// 资产类型
	AssetTypeImage = "image"
	AssetTypeVideo = "video"
	AssetTypeAudio = "audio"

	// 媒体角色
	MediaRoleBgImage     = "bg_image"
	MediaRoleCutoutImage = "cutout_image"
	MediaRoleAvatar      = "avatar"
	MediaRoleGallery     = "gallery"

	// 模板类型
	TemplateTypeTxt2Img   = "txt2img"
	TemplateTypeImg2Img   = "img2img"
	TemplateTypeImg2Video = "img2video"
	TemplateTypeTxt2Video = "txt2video"
)
